- name: Install postgresql
  apt: 
    name: postgresql
    state: present

- name: Install postgresql
  apt: 
    name: postgresql-client
    state: present

- name: Ensure psycopg2 is installed
  package:
    name: python-psycopg2
    state: present